// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/table/*": {
    params: {
      "*": string;
    };
  };
  "/counter/*": {
    params: {
      "*": string;
    };
  };
  "/people/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/table/*" | "/counter/*" | "/people/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/table.$.tsx": {
    id: "routes/table.$";
    page: "/table/*";
  };
  "routes/counter.$.tsx": {
    id: "routes/counter.$";
    page: "/counter/*";
  };
  "routes/people.$.tsx": {
    id: "routes/people.$";
    page: "/people/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/table.$": typeof import("./app/routes/table.$.tsx");
  "routes/counter.$": typeof import("./app/routes/counter.$.tsx");
  "routes/people.$": typeof import("./app/routes/people.$.tsx");
};